# Generated by Django 3.2.4 on 2021-06-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210620_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
